//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headway.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Config()
        {
            this.ConfigContainers = new HashSet<ConfigContainer>();
            this.ConfigItems = new HashSet<ConfigItem>();
            this.ConfigSearchItems = new HashSet<ConfigSearchItem>();
        }
    
        public int ConfigId { get; set; }
        public bool NavigateResetBreadcrumb { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Model { get; set; }
        public string ModelApi { get; set; }
        public string OrderModelBy { get; set; }
        public string Document { get; set; }
        public string NavigatePage { get; set; }
        public string NavigateProperty { get; set; }
        public string NavigateConfig { get; set; }
        public bool CreateLocal { get; set; }
        public string DocumentArgs { get; set; }
        public string SearchComponent { get; set; }
        public bool UseSearchComponent { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigContainer> ConfigContainers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigItem> ConfigItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigSearchItem> ConfigSearchItems { get; set; }
    }
}
