//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headway.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DemoModel()
        {
            this.DemoModelItems = new HashSet<DemoModelItem>();
            this.DemoModelTreeItems = new HashSet<DemoModelTreeItem>();
        }
    
        public int DemoModelId { get; set; }
        public bool Checkbox { get; set; }
        public int Integer { get; set; }
        public string OptionVertical { get; set; }
        public string OptionHorizontal { get; set; }
        public string Dropdown { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> DropdownComplexId { get; set; }
        public string Text { get; set; }
        public string TextMultiline { get; set; }
        public decimal Decimal { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual DemoModelComplexProperty DemoModelComplexProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemoModelItem> DemoModelItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemoModelTreeItem> DemoModelTreeItems { get; set; }
    }
}
