//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headway.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoModelItem
    {
        public int DemoModelItemId { get; set; }
        public int DemoModelId { get; set; }
        public int Order { get; set; }
        public string Name { get; set; }
    
        public virtual DemoModel DemoModel { get; set; }
    }
}
