//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headway.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeadwayEntities3 : DbContext
    {
        public HeadwayEntities3()
            : base("name=HeadwayEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ConfigContainer> ConfigContainers { get; set; }
        public virtual DbSet<ConfigItem> ConfigItems { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<ConfigSearchItem> ConfigSearchItems { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DemoModelComplexProperty> DemoModelComplexProperties { get; set; }
        public virtual DbSet<DemoModelItem> DemoModelItems { get; set; }
        public virtual DbSet<DemoModel> DemoModels { get; set; }
        public virtual DbSet<DemoModelTreeItem> DemoModelTreeItems { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Redress> Redresses { get; set; }
        public virtual DbSet<RefundCalculation> RefundCalculations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
