//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headway.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Redress
    {
        public int RedressId { get; set; }
        public int CustomerId { get; set; }
        public int ProgramId { get; set; }
        public Nullable<int> RefundCalculationId { get; set; }
        public Nullable<int> RefundVerificationRefundCalculationId { get; set; }
        public string RedressCaseOwner { get; set; }
        public string RedressCreateBy { get; set; }
        public Nullable<System.DateTime> RedressCreateDate { get; set; }
        public string RefundReviewStatus { get; set; }
        public string RefundReviewComment { get; set; }
        public string RefundReviewBy { get; set; }
        public Nullable<System.DateTime> RefundReviewDate { get; set; }
        public string RedressReviewStatus { get; set; }
        public string RedressReviewComment { get; set; }
        public string RedressReviewBy { get; set; }
        public Nullable<System.DateTime> RedressReviewDate { get; set; }
        public string RedressValidationStatus { get; set; }
        public string RedressValidationComment { get; set; }
        public string RedressValidationBy { get; set; }
        public Nullable<System.DateTime> RedressValidationDate { get; set; }
        public string CommunicationGenerationStatus { get; set; }
        public string CommunicationGenerationBy { get; set; }
        public Nullable<System.DateTime> CommunicationGenerationDate { get; set; }
        public string CommunicationDispatchStatus { get; set; }
        public string CommunicationDispatchComment { get; set; }
        public string CommunicationDispatchBy { get; set; }
        public Nullable<System.DateTime> CommunicationDispatchDate { get; set; }
        public Nullable<bool> ResponseRequired { get; set; }
        public Nullable<bool> ResponseReceived { get; set; }
        public string AwaitingResponseStatus { get; set; }
        public string AwaitingResponseComment { get; set; }
        public string AwaitingResponseBy { get; set; }
        public Nullable<System.DateTime> AwaitingResponseDate { get; set; }
        public string PaymentGenerationStatus { get; set; }
        public string PaymentGenerationBy { get; set; }
        public Nullable<System.DateTime> PaymentGenerationDate { get; set; }
        public string FinalRedressReviewStatus { get; set; }
        public string FinalRedressReviewComment { get; set; }
        public string FinalRedressReviewBy { get; set; }
        public Nullable<System.DateTime> FinalRedressReviewDate { get; set; }
        public int ProductId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Program Program { get; set; }
        public virtual RefundCalculation RefundCalculation { get; set; }
        public virtual RefundCalculation RefundCalculation1 { get; set; }
    }
}
