//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headway.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundCalculation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefundCalculation()
        {
            this.Redresses = new HashSet<Redress>();
            this.Redresses1 = new HashSet<Redress>();
        }
    
        public int RefundCalculationId { get; set; }
        public Nullable<decimal> BasicRefundAmount { get; set; }
        public Nullable<decimal> CompensatoryAmount { get; set; }
        public Nullable<decimal> CompensatoryInterestAmount { get; set; }
        public Nullable<decimal> TotalCompensatoryAmount { get; set; }
        public Nullable<decimal> TotalRefundAmount { get; set; }
        public Nullable<System.DateTime> CalculatedDate { get; set; }
        public string CalculatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redress> Redresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redress> Redresses1 { get; set; }
    }
}
